-- Fallback Database Schema
CREATE DATABASE IF NOT EXISTS traffic_violation_db;
USE traffic_violation_db;

DROP TABLE IF EXISTS VIOLATION;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS OWNER;

CREATE TABLE OWNER (
    Owner_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    License_No VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE VEHICLE (
    Vehicle_No VARCHAR(20) PRIMARY KEY,
    Owner_ID INT NOT NULL,
    Model VARCHAR(100) NOT NULL,
    FOREIGN KEY (Owner_ID) REFERENCES OWNER(Owner_ID) ON DELETE CASCADE
);

CREATE TABLE VIOLATION (
    Violation_ID INT AUTO_INCREMENT PRIMARY KEY,
    Vehicle_No VARCHAR(20) NOT NULL,
    Type VARCHAR(100) NOT NULL,
    Fine_Amount DECIMAL(10, 2) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    FOREIGN KEY (Vehicle_No) REFERENCES VEHICLE(Vehicle_No) ON DELETE CASCADE
);